import { Layout } from "@/components/layout/Layout";

const LAST_UPDATED = "April 8, 2026";

export default function PrivacyPolicy() {
  return (
    <Layout>
      <div className="max-w-3xl mx-auto px-6 py-16">
        <div className="mb-10">
          <h1 className="text-4xl font-bold mb-3">Privacy Policy</h1>
          <p className="text-muted-foreground">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="space-y-10 text-[15px] leading-relaxed">
          <section>
            <p className="text-muted-foreground">
              NepalTrails ("we", "us", or "our") is committed to protecting your
              personal information. This Privacy Policy explains what data we
              collect, how we use it, and your rights regarding that data. By
              using the Platform, you agree to the practices described below.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              1. Data We Collect
            </h2>
            <p className="text-muted-foreground mb-3">
              We collect information you provide directly and information
              generated by your use of the Platform:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>
                <span className="font-medium text-foreground">Account data:</span>{" "}
                Name, email address, and password (stored as a secure hash) when
                you register.
              </li>
              <li>
                <span className="font-medium text-foreground">Booking data:</span>{" "}
                Trip details, guest counts, travel dates, and payment records
                associated with your bookings.
              </li>
              <li>
                <span className="font-medium text-foreground">
                  Communication data:
                </span>{" "}
                Messages or reviews you submit through the Platform.
              </li>
              <li>
                <span className="font-medium text-foreground">Usage data:</span>{" "}
                Pages visited, features used, timestamps, browser type, and IP
                address, collected automatically.
              </li>
              <li>
                <span className="font-medium text-foreground">
                  Payment data:
                </span>{" "}
                We do not store your full card number. Payment is handled by
                Stripe, which has its own privacy policy.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              2. How We Use Your Data
            </h2>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>To create and manage your account.</li>
              <li>
                To process bookings and communicate booking confirmations,
                updates, and reminders.
              </li>
              <li>
                To facilitate payments between travelers and travel agencies.
              </li>
              <li>
                To display reviews and ratings to help other travelers make
                informed decisions.
              </li>
              <li>
                To improve the Platform through analytics and performance
                monitoring.
              </li>
              <li>
                To send you service-related emails (e.g., password reset,
                booking receipt). We will not send unsolicited marketing emails
                without your consent.
              </li>
              <li>To comply with legal obligations.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              3. Third-Party Services
            </h2>
            <p className="text-muted-foreground mb-3">
              We use the following third-party services that may process your
              data:
            </p>
            <div className="space-y-4">
              <div className="p-4 bg-muted/50 rounded-xl">
                <p className="font-medium mb-1">Supabase</p>
                <p className="text-sm text-muted-foreground">
                  Our database and authentication provider. Your account data and
                  booking records are stored securely on Supabase infrastructure.
                  Supabase is SOC 2 Type II certified and stores data in servers
                  located in the EU (Frankfurt) by default.
                </p>
              </div>
              <div className="p-4 bg-muted/50 rounded-xl">
                <p className="font-medium mb-1">Stripe</p>
                <p className="text-sm text-muted-foreground">
                  Our payment processor. When you make a payment, your card
                  details are sent directly to Stripe and never touch our
                  servers. Stripe is PCI DSS Level 1 certified. See Stripe's
                  privacy policy at stripe.com/privacy.
                </p>
              </div>
              <div className="p-4 bg-muted/50 rounded-xl">
                <p className="font-medium mb-1">Google (OAuth)</p>
                <p className="text-sm text-muted-foreground">
                  If you choose to sign in with Google, we receive your name and
                  email address from Google. We do not access any other Google
                  account data.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. Cookies</h2>
            <p className="text-muted-foreground mb-3">
              We use cookies and similar technologies to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>
                Keep you signed in between sessions (authentication cookies).
              </li>
              <li>Remember your preferences and search filters.</li>
              <li>Analyze how the Platform is used so we can improve it.</li>
            </ul>
            <p className="text-muted-foreground mt-3">
              You can disable cookies in your browser settings. Note that doing
              so may prevent some features from working correctly, including
              staying logged in.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              5. Data Sharing & Disclosure
            </h2>
            <p className="text-muted-foreground mb-3">
              We share your data only in the following circumstances:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>
                <span className="font-medium text-foreground">
                  With travel agencies:
                </span>{" "}
                When you book, we share your name, contact information, and
                booking details with the agency providing the service.
              </li>
              <li>
                <span className="font-medium text-foreground">
                  With service providers:
                </span>{" "}
                As described in Section 3, we use Supabase and Stripe to operate
                the Platform.
              </li>
              <li>
                <span className="font-medium text-foreground">
                  Legal requirements:
                </span>{" "}
                We may disclose data if required by law or in response to a valid
                legal request.
              </li>
            </ul>
            <p className="text-muted-foreground mt-3">
              We do not sell your personal data to third parties.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. Data Retention</h2>
            <p className="text-muted-foreground">
              We retain your personal data for as long as your account is active
              or as needed to provide you with our services. If you delete your
              account, we will delete or anonymize your personal data within 30
              days, except where we are required to retain it for legal or
              accounting purposes (e.g., completed transaction records).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Your Rights</h2>
            <p className="text-muted-foreground mb-3">
              Depending on your location, you may have the following rights
              regarding your personal data:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>
                <span className="font-medium text-foreground">Access:</span> Request
                a copy of the personal data we hold about you.
              </li>
              <li>
                <span className="font-medium text-foreground">Correction:</span>{" "}
                Ask us to correct inaccurate or incomplete data.
              </li>
              <li>
                <span className="font-medium text-foreground">Deletion:</span>{" "}
                Request that we delete your account and associated data.
              </li>
              <li>
                <span className="font-medium text-foreground">Portability:</span>{" "}
                Receive your data in a structured, machine-readable format.
              </li>
              <li>
                <span className="font-medium text-foreground">Objection:</span>{" "}
                Object to certain processing of your data, including for direct
                marketing purposes.
              </li>
            </ul>
            <p className="text-muted-foreground mt-3">
              To exercise any of these rights, contact us at{" "}
              <a
                href="mailto:privacy@nepaltrails.com"
                className="text-primary hover:underline"
              >
                privacy@nepaltrails.com
              </a>
              . We will respond within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">
              8. Changes to This Policy
            </h2>
            <p className="text-muted-foreground">
              We may update this Privacy Policy from time to time. We will
              notify you of material changes by updating the "Last updated" date
              and, where appropriate, sending an email notification. Continued
              use of the Platform after changes constitutes acceptance of the
              revised Policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. Contact Us</h2>
            <p className="text-muted-foreground">
              If you have any questions or concerns about this Privacy Policy or
              how we handle your data, please contact us at{" "}
              <a
                href="mailto:privacy@nepaltrails.com"
                className="text-primary hover:underline"
              >
                privacy@nepaltrails.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </Layout>
  );
}
